---

- name: PERCONA_XTRADB | Get default PXC configuration file
  slurp:
    src: "{{ percona_xtradb_global_config_file }}"
  register: pxcglobalconfig
  tags:
    - percona_xtradb_configure

- name: PERCONA_XTRADB | Setting fact global PXC configuration path
  set_fact:
    percona_xtradb_config_file_path: "{{ pxcglobalconfig.content | b64decode | regex_search('/etc/mysql/.*.conf.d') }}"
  tags:
    - percona_xtradb_configure

- name: PERCONA_XTRADB | Copy global PXC configuration
  template:
    src: mysql/conf/wsrep.cnf.j2
    dest: "{{ percona_xtradb_config_file_path }}/{{ percona_xtradb_config_file_name }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
  tags:
    - percona_xtradb_configure

- name: PERCONA_XTRADB | Ensure additional options file include dir exists
  file:
    path: "{{ percona_mysql_extra_conf_include_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - percona_xtradb_configure

- name: PERCONA_XTRADB | Copy extra option files templates (provided by playbooks)
  template:
    src: "{{ item.src }}"
    dest: "{{ percona_mysql_extra_conf_include_dir }}/{{ item.path | splitext | first }}"  # This is to remove .j2 extension
    owner: root
    group: root
    mode: 0644
  with_filetree:
    - "{{ percona_mysql_extra_conf_template_playbook_path }}/"
  when: item.state == "file"
  notify: restart mysql
  tags:
    - percona_xtradb_configure

- name: PERCONA_XTRADB | Ensure datadir exists
  file:
    path: "{{ percona_mysql_datadir }}"
    state: directory
    owner: "{{ percona_mysql_user }}"
    group: "{{ percona_mysql_group }}"
    mode: 0750
  tags:
    - percona_xtradb_configure
