---

- name: PERCONA_XTRADB | Install
  include: install.yml
  tags:
    - percona_xtradb_install

- name: PERCONA_XTRADB | Configure
  include: config.yml
  tags:
    - percona_xtradb_configure

- name: PERCONA_XTRADB | Secure traffic
  include: secure_traffic.yml
  when: percona_xtradb_secure_cluster_traffic
  tags:
    - percona_xtradb_secure_traffic

- name: PERCONA_XTRADB | Bootstrap
  include: bootstrap.yml
  tags:
    - percona_xtradb_bootstrap

- name: PERCONA_XTRADB | Users
  include: users.yml
  when:
    - percona_xtradb_bind_address == percona_xtradb_master_node
  tags:
    - percona_xtradb_users
    - percona_xtradb_configure

- name: PERCONA_XTRADB | Databases
  include: databases.yml
  when:
    - percona_xtradb_bind_address == percona_xtradb_master_node
  tags:
    - percona_xtradb_databases
    - percona_xtradb_configure
