---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: perconaxtradb1
    groups:
      - percona_xtradb_group
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: false
    security_opts:
      - apparmor=unconfined
    exposed_ports:
      - 3306/tcp
      - 4444/tcp
      - 4567/tcp
      - 4568/tcp
    capabilities:
      - SYS_ADMIN
      - SYS_NICE
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
  - name: perconaxtradb2
    groups:
      - percona_xtradb_group
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: false
    security_opts:
      - apparmor=unconfined
    exposed_ports:
      - 3306/tcp
      - 4444/tcp
      - 4567/tcp
      - 4568/tcp
    capabilities:
      - SYS_ADMIN
      - SYS_NICE
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
  - name: perconaxtradb3
    groups:
      - percona_xtradb_group
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: false
    security_opts:
      - apparmor=unconfined
    exposed_ports:
      - 3306/tcp
      - 4444/tcp
      - 4567/tcp
      - 4568/tcp
    capabilities:
      - SYS_ADMIN
      - SYS_NICE
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
provisioner:
  name: ansible
verifier:
  name: ansible
